// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/importers/migration.proto

package importers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED Algorithm = 0
	Algorithm_SHA1                  Algorithm = 1
	Algorithm_SHA256                Algorithm = 2
	Algorithm_SHA512                Algorithm = 3
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "SHA1",
		2: "SHA256",
		3: "SHA512",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"SHA1":                  1,
		"SHA256":                2,
		"SHA512":                3,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_importers_migration_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_internal_importers_migration_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_internal_importers_migration_proto_rawDescGZIP(), []int{0}
}

type DigitCount int32

const (
	DigitCount_DIGIT_COUNT_UNSPECIFIED DigitCount = 0
	DigitCount_SIX                     DigitCount = 1
	DigitCount_EIGHT                   DigitCount = 2
)

// Enum value maps for DigitCount.
var (
	DigitCount_name = map[int32]string{
		0: "DIGIT_COUNT_UNSPECIFIED",
		1: "SIX",
		2: "EIGHT",
	}
	DigitCount_value = map[string]int32{
		"DIGIT_COUNT_UNSPECIFIED": 0,
		"SIX":                     1,
		"EIGHT":                   2,
	}
)

func (x DigitCount) Enum() *DigitCount {
	p := new(DigitCount)
	*p = x
	return p
}

func (x DigitCount) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DigitCount) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_importers_migration_proto_enumTypes[1].Descriptor()
}

func (DigitCount) Type() protoreflect.EnumType {
	return &file_internal_importers_migration_proto_enumTypes[1]
}

func (x DigitCount) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DigitCount.Descriptor instead.
func (DigitCount) EnumDescriptor() ([]byte, []int) {
	return file_internal_importers_migration_proto_rawDescGZIP(), []int{1}
}

type OtpType int32

const (
	OtpType_OTP_TYPE_UNSPECIFIED OtpType = 0
	OtpType_HOTP                 OtpType = 1
	OtpType_TOTP                 OtpType = 2
)

// Enum value maps for OtpType.
var (
	OtpType_name = map[int32]string{
		0: "OTP_TYPE_UNSPECIFIED",
		1: "HOTP",
		2: "TOTP",
	}
	OtpType_value = map[string]int32{
		"OTP_TYPE_UNSPECIFIED": 0,
		"HOTP":                 1,
		"TOTP":                 2,
	}
)

func (x OtpType) Enum() *OtpType {
	p := new(OtpType)
	*p = x
	return p
}

func (x OtpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtpType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_importers_migration_proto_enumTypes[2].Descriptor()
}

func (OtpType) Type() protoreflect.EnumType {
	return &file_internal_importers_migration_proto_enumTypes[2]
}

func (x OtpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtpType.Descriptor instead.
func (OtpType) EnumDescriptor() ([]byte, []int) {
	return file_internal_importers_migration_proto_rawDescGZIP(), []int{2}
}

// MigrationPayload contains the migration data
type MigrationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpAccounts   []*OTPAccount          `protobuf:"bytes,1,rep,name=otp_accounts,json=otpAccounts,proto3" json:"otp_accounts,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BatchSize     int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchIndex    int32                  `protobuf:"varint,4,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	BatchId       int32                  `protobuf:"varint,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationPayload) Reset() {
	*x = MigrationPayload{}
	mi := &file_internal_importers_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationPayload) ProtoMessage() {}

func (x *MigrationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_importers_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationPayload.ProtoReflect.Descriptor instead.
func (*MigrationPayload) Descriptor() ([]byte, []int) {
	return file_internal_importers_migration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationPayload) GetOtpAccounts() []*OTPAccount {
	if x != nil {
		return x.OtpAccounts
	}
	return nil
}

func (x *MigrationPayload) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MigrationPayload) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *MigrationPayload) GetBatchIndex() int32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *MigrationPayload) GetBatchId() int32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

// OTPAccount represents a single TOTP account
type OTPAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Algorithm     Algorithm              `protobuf:"varint,4,opt,name=algorithm,proto3,enum=google.authenticator.migration.Algorithm" json:"algorithm,omitempty"`
	Digits        DigitCount             `protobuf:"varint,5,opt,name=digits,proto3,enum=google.authenticator.migration.DigitCount" json:"digits,omitempty"`
	Type          OtpType                `protobuf:"varint,6,opt,name=type,proto3,enum=google.authenticator.migration.OtpType" json:"type,omitempty"`
	Counter       int64                  `protobuf:"varint,7,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTPAccount) Reset() {
	*x = OTPAccount{}
	mi := &file_internal_importers_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTPAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTPAccount) ProtoMessage() {}

func (x *OTPAccount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_importers_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTPAccount.ProtoReflect.Descriptor instead.
func (*OTPAccount) Descriptor() ([]byte, []int) {
	return file_internal_importers_migration_proto_rawDescGZIP(), []int{1}
}

func (x *OTPAccount) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *OTPAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OTPAccount) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *OTPAccount) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *OTPAccount) GetDigits() DigitCount {
	if x != nil {
		return x.Digits
	}
	return DigitCount_DIGIT_COUNT_UNSPECIFIED
}

func (x *OTPAccount) GetType() OtpType {
	if x != nil {
		return x.Type
	}
	return OtpType_OTP_TYPE_UNSPECIFIED
}

func (x *OTPAccount) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

var File_internal_importers_migration_proto protoreflect.FileDescriptor

const file_internal_importers_migration_proto_rawDesc = "" +
	"\n" +
	"\"internal/importers/migration.proto\x12\x1egoogle.authenticator.migration\"\xd6\x01\n" +
	"\x10MigrationPayload\x12M\n" +
	"\fotp_accounts\x18\x01 \x03(\v2*.google.authenticator.migration.OTPAccountR\votpAccounts\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12\x1f\n" +
	"\vbatch_index\x18\x04 \x01(\x05R\n" +
	"batchIndex\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\x05R\abatchId\"\xb4\x02\n" +
	"\n" +
	"OTPAccount\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12G\n" +
	"\talgorithm\x18\x04 \x01(\x0e2).google.authenticator.migration.AlgorithmR\talgorithm\x12B\n" +
	"\x06digits\x18\x05 \x01(\x0e2*.google.authenticator.migration.DigitCountR\x06digits\x12;\n" +
	"\x04type\x18\x06 \x01(\x0e2'.google.authenticator.migration.OtpTypeR\x04type\x12\x18\n" +
	"\acounter\x18\a \x01(\x03R\acounter*H\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04SHA1\x10\x01\x12\n" +
	"\n" +
	"\x06SHA256\x10\x02\x12\n" +
	"\n" +
	"\x06SHA512\x10\x03*=\n" +
	"\n" +
	"DigitCount\x12\x1b\n" +
	"\x17DIGIT_COUNT_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03SIX\x10\x01\x12\t\n" +
	"\x05EIGHT\x10\x02*7\n" +
	"\aOtpType\x12\x18\n" +
	"\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HOTP\x10\x01\x12\b\n" +
	"\x04TOTP\x10\x02B.Z,github.com/zulfikawr/gotp/internal/importersb\x06proto3"

var (
	file_internal_importers_migration_proto_rawDescOnce sync.Once
	file_internal_importers_migration_proto_rawDescData []byte
)

func file_internal_importers_migration_proto_rawDescGZIP() []byte {
	file_internal_importers_migration_proto_rawDescOnce.Do(func() {
		file_internal_importers_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_importers_migration_proto_rawDesc), len(file_internal_importers_migration_proto_rawDesc)))
	})
	return file_internal_importers_migration_proto_rawDescData
}

var file_internal_importers_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_importers_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_importers_migration_proto_goTypes = []any{
	(Algorithm)(0),           // 0: google.authenticator.migration.Algorithm
	(DigitCount)(0),          // 1: google.authenticator.migration.DigitCount
	(OtpType)(0),             // 2: google.authenticator.migration.OtpType
	(*MigrationPayload)(nil), // 3: google.authenticator.migration.MigrationPayload
	(*OTPAccount)(nil),       // 4: google.authenticator.migration.OTPAccount
}
var file_internal_importers_migration_proto_depIdxs = []int32{
	4, // 0: google.authenticator.migration.MigrationPayload.otp_accounts:type_name -> google.authenticator.migration.OTPAccount
	0, // 1: google.authenticator.migration.OTPAccount.algorithm:type_name -> google.authenticator.migration.Algorithm
	1, // 2: google.authenticator.migration.OTPAccount.digits:type_name -> google.authenticator.migration.DigitCount
	2, // 3: google.authenticator.migration.OTPAccount.type:type_name -> google.authenticator.migration.OtpType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_importers_migration_proto_init() }
func file_internal_importers_migration_proto_init() {
	if File_internal_importers_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_importers_migration_proto_rawDesc), len(file_internal_importers_migration_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_importers_migration_proto_goTypes,
		DependencyIndexes: file_internal_importers_migration_proto_depIdxs,
		EnumInfos:         file_internal_importers_migration_proto_enumTypes,
		MessageInfos:      file_internal_importers_migration_proto_msgTypes,
	}.Build()
	File_internal_importers_migration_proto = out.File
	file_internal_importers_migration_proto_goTypes = nil
	file_internal_importers_migration_proto_depIdxs = nil
}
